import { CanonicalResumeType } from './schemas';
import { esc, safeUrl } from './latex';

export interface PageFitOptions {
  marginInches?: number;
  fontSizePt?: 10 | 11;
  itemSepPt?: number;
  mode?: 'Conservative' | 'Focused';
}

export interface PageBudgetReport {
  estimatedLines: number;
  recommendedPages: number;
  marginInches: number;
  fontSizePt: number;
  itemSepPt: number;
}

/**
 * Deterministic Page-Fit Budget loop (Section 4.5).
 * Calculates estimated vertical content lines and adjusts spacing/margins.
 */
export function calculatePageBudget(
  resume: CanonicalResumeType,
  targetPages: 1 | 2 = 1
): PageBudgetReport {
  let estimatedLines = 4; // Header & contacts

  if (resume.summary) {
    estimatedLines += Math.ceil(resume.summary.length / 85) + 2;
  }

  // Skills
  for (const s of resume.skills) {
    estimatedLines += 1 + Math.ceil(s.items.join(', ').length / 80);
  }
  if (resume.skills.length > 0) estimatedLines += 2;

  // Experience
  for (const exp of resume.experience) {
    estimatedLines += 2; // Org, title, dates
    for (const b of exp.bullets) {
      estimatedLines += Math.max(1, Math.ceil(b.text.length / 85));
    }
  }
  if (resume.experience.length > 0) estimatedLines += 2;

  // Projects
  for (const proj of resume.projects) {
    estimatedLines += 2;
    for (const b of proj.bullets) {
      estimatedLines += Math.max(1, Math.ceil(b.text.length / 85));
    }
  }
  if (resume.projects.length > 0) estimatedLines += 2;

  // Education
  estimatedLines += resume.education.length * 2;
  if (resume.education.length > 0) estimatedLines += 2;

  // Certifications
  if (resume.certifications.length > 0) {
    estimatedLines += resume.certifications.length + 2;
  }

  // Achievements
  if (resume.achievements.length > 0) {
    estimatedLines += resume.achievements.length + 2;
  }

  // Page budget thresholds (approx 52 lines for 1-page at 10pt with 0.75in margins)
  let marginInches = 0.75;
  const fontSizePt: 10 | 11 = 10;
  let itemSepPt = 2;
  let recommendedPages = 1;

  if (targetPages === 1 && estimatedLines > 48) {
    // Stage 1: Tighten margins
    marginInches = 0.6;
    itemSepPt = 1.5;
  }
  if (targetPages === 1 && estimatedLines > 56) {
    // Stage 2: Tighten spacing further
    marginInches = 0.5;
    itemSepPt = 1;
  }
  if (targetPages === 1 && estimatedLines > 65) {
    // Exceeds single page budget comfortably; recommend 2 pages
    recommendedPages = 2;
    marginInches = 0.75;
    itemSepPt = 2;
  }

  return {
    estimatedLines,
    recommendedPages,
    marginInches,
    fontSizePt,
    itemSepPt,
  };
}

/**
 * Compiles CanonicalResume into high-fidelity, single-column ATS LaTeX.
 * Adheres to Section 4.6 (no shell escape, strictly escaped macros, fixed fonts).
 */
export function compileCanonicalToLatex(
  resume: CanonicalResumeType,
  options?: PageFitOptions
): string {
  const budget = calculatePageBudget(resume);
  const margin = options?.marginInches ?? budget.marginInches;
  const fontSize = options?.fontSizePt ?? budget.fontSizePt;
  const itemSep = options?.itemSepPt ?? budget.itemSepPt;

  const escapedName = esc(resume.basics.name);

  // Format contact line with clickable, sanitized hrefs
  const contactParts: string[] = [];
  if (resume.basics.email) {
    contactParts.push(`\\href{mailto:${resume.basics.email}}{${esc(resume.basics.email)}}`);
  }
  if (resume.basics.phone) {
    contactParts.push(esc(resume.basics.phone));
  }
  if (resume.basics.location) {
    contactParts.push(esc(resume.basics.location));
  }
  for (const l of resume.basics.links) {
    const safe = safeUrl(l.url);
    if (safe) {
      contactParts.push(`\\href{${safe}}{${esc(l.label)}}`);
    } else {
      contactParts.push(esc(l.label));
    }
  }
  const contactLine = contactParts.join(' \\ \\textbullet\\ \\ ');

  let latex = `% Generated by Resurox - Single-Column ATS Clean Template
\\documentclass[${fontSize}pt,letterpaper]{article}
\\usepackage[margin=${margin}in]{geometry}
\\usepackage[hidelinks]{hyperref}
\\usepackage{enumitem}
\\pagestyle{empty}

\\begin{document}

\\begin{center}
  {\\LARGE \\textbf{${escapedName}}}\\\\[4pt]
  {\\small ${contactLine}}
\\end{center}
\\vspace{4pt}
`;

  // Summary
  if (resume.summary && resume.summary.trim().length > 0) {
    latex += `\\noindent{\\large \\textbf{PROFESSIONAL SUMMARY}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
{\\small ${esc(resume.summary)}}
\\vspace{6pt}

`;
  }

  // Skills
  if (resume.skills.length > 0) {
    latex += `\\noindent{\\large \\textbf{TECHNICAL SKILLS}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
\\begin{itemize}[leftmargin=1.5em, itemsep=${itemSep}pt, parsep=0pt]
`;
    for (const group of resume.skills) {
      latex += `  \\item \\textbf{${esc(group.category)}:} ${esc(group.items.join(', '))}\n`;
    }
    latex += `\\end{itemize}
\\vspace{6pt}

`;
  }

  // Experience
  if (resume.experience.length > 0) {
    latex += `\\noindent{\\large \\textbf{PROFESSIONAL EXPERIENCE}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
`;
    for (const exp of resume.experience) {
      const dates = [exp.start, exp.end].filter(Boolean).join(' -- ');
      latex += `\\noindent\\textbf{${esc(exp.title)}} \\hfill {\\small ${esc(dates)}}\\\\
\\textit{${esc(exp.org)}}${exp.location ? ` \\hfill {\\small \\textit{${esc(exp.location)}}}` : ''}
\\begin{itemize}[leftmargin=1.5em, itemsep=${itemSep}pt, parsep=0pt]
`;
      for (const b of exp.bullets) {
        latex += `  \\item ${esc(b.text)}\n`;
      }
      latex += `\\end{itemize}
\\vspace{4pt}
`;
    }
    latex += `\\vspace{4pt}\n\n`;
  }

  // Projects
  if (resume.projects.length > 0) {
    latex += `\\noindent{\\large \\textbf{PROJECTS}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
`;
    for (const proj of resume.projects) {
      const techList = proj.tech.length > 0 ? ` [${proj.tech.join(', ')}]` : '';
      latex += `\\noindent\\textbf{${esc(proj.name)}}${esc(techList)}`;
      if (proj.link) {
        const safe = safeUrl(proj.link);
        if (safe) {
          latex += ` \\hfill {\\small \\href{${safe}}{Project Link}}`;
        }
      }
      latex += `\\\\
\\begin{itemize}[leftmargin=1.5em, itemsep=${itemSep}pt, parsep=0pt]
`;
      for (const b of proj.bullets) {
        latex += `  \\item ${esc(b.text)}\n`;
      }
      latex += `\\end{itemize}
\\vspace{4pt}
`;
    }
    latex += `\\vspace{4pt}\n\n`;
  }

  // Education
  if (resume.education.length > 0) {
    latex += `\\noindent{\\large \\textbf{EDUCATION}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
`;
    for (const edu of resume.education) {
      const dates = [edu.start, edu.end].filter(Boolean).join(' -- ');
      const degreeStr = `${edu.degree}${edu.field ? ` in ${edu.field}` : ''}`;
      latex += `\\noindent\\textbf{${esc(edu.institution)}} \\hfill {\\small ${esc(dates)}}\\\\
${esc(degreeStr)}${edu.grade ? ` -- ${esc(edu.grade)}` : ''}\\\\
`;
      if (edu.coursework && edu.coursework.length > 0) {
        latex += `{\\small \\textit{Relevant Coursework: ${esc(edu.coursework.join(', '))}}}\\\\
`;
      }
      latex += `\\vspace{2pt}\n`;
    }
    latex += `\\vspace{4pt}\n\n`;
  }

  // Certifications
  if (resume.certifications.length > 0) {
    latex += `\\noindent{\\large \\textbf{CERTIFICATIONS}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
\\begin{itemize}[leftmargin=1.5em, itemsep=${itemSep}pt, parsep=0pt]
`;
    for (const cert of resume.certifications) {
      const issuer = cert.issuer ? ` (${cert.issuer})` : '';
      const date = cert.date ? ` -- ${cert.date}` : '';
      latex += `  \\item ${esc(cert.name)}${esc(issuer)}${esc(date)}\n`;
    }
    latex += `\\end{itemize}
\\vspace{6pt}

`;
  }

  // Other Sections (Awards, Languages, etc.)
  for (const oth of resume.other) {
    latex += `\\noindent{\\large \\textbf{${esc(oth.heading.toUpperCase())}}}\\\\[-4pt]
\\rule{\\linewidth}{0.5pt}\\\\[4pt]
\\begin{itemize}[leftmargin=1.5em, itemsep=${itemSep}pt, parsep=0pt]
`;
    for (const line of oth.lines) {
      latex += `  \\item ${esc(line.text)}\n`;
    }
    latex += `\\end{itemize}
\\vspace{6pt}

`;
  }

  latex += `\\end{document}\n`;
  return latex;
}

/**
 * Compiles CanonicalResume into clean plaintext ATS layout.
 */
export function compileCanonicalToPlainText(resume: CanonicalResumeType): string {
  const parts: string[] = [];

  parts.push(resume.basics.name.toUpperCase());
  const contacts = [
    resume.basics.email,
    resume.basics.phone,
    resume.basics.location,
    ...resume.basics.links.map((l) => `${l.label}: ${l.url}`),
  ]
    .filter(Boolean)
    .join(' | ');
  if (contacts) parts.push(contacts);
  parts.push('='.repeat(50));

  if (resume.summary) {
    parts.push('\nPROFESSIONAL SUMMARY');
    parts.push(resume.summary);
  }

  if (resume.skills.length > 0) {
    parts.push('\nTECHNICAL SKILLS');
    for (const s of resume.skills) {
      parts.push(`${s.category}: ${s.items.join(', ')}`);
    }
  }

  if (resume.experience.length > 0) {
    parts.push('\nPROFESSIONAL EXPERIENCE');
    for (const exp of resume.experience) {
      const dates = [exp.start, exp.end].filter(Boolean).join(' - ');
      parts.push(`${exp.title} | ${exp.org}${dates ? ` | ${dates}` : ''}`);
      for (const b of exp.bullets) {
        parts.push(`  • ${b.text}`);
      }
    }
  }

  if (resume.projects.length > 0) {
    parts.push('\nPROJECTS');
    for (const p of resume.projects) {
      const tech = p.tech.length > 0 ? ` (${p.tech.join(', ')})` : '';
      parts.push(`${p.name}${tech}${p.link ? ` [${p.link}]` : ''}`);
      for (const b of p.bullets) {
        parts.push(`  • ${b.text}`);
      }
    }
  }

  if (resume.education.length > 0) {
    parts.push('\nEDUCATION');
    for (const edu of resume.education) {
      const dates = [edu.start, edu.end].filter(Boolean).join(' - ');
      parts.push(`${edu.degree}${edu.field ? ` in ${edu.field}` : ''} - ${edu.institution}${dates ? ` (${dates})` : ''}`);
    }
  }

  if (resume.certifications.length > 0) {
    parts.push('\nCERTIFICATIONS');
    for (const c of resume.certifications) {
      parts.push(`  • ${c.name}${c.issuer ? ` (${c.issuer})` : ''}`);
    }
  }

  for (const oth of resume.other) {
    parts.push(`\n${oth.heading.toUpperCase()}`);
    for (const l of oth.lines) {
      parts.push(`  • ${l.text}`);
    }
  }

  return parts.join('\n');
}
